Add Combined dependency manager file
Anish-M-code/pqcrypt pull request #19
Opened 2023-10-04 17:52 UTC by ATamblingPoder

This file will enable us to remove all the different distro_install.sh scripts for ease of use.
Suggestions welcome! :)
Regards

2023-10-07 11:21 UTC, Anish-M-code requested changes

2023-10-07 11:21 UTC, Anish-M-code commented on check_deps.sh
> +	rm -rf liboqs
I guess we don't need to remove liboqs folder at present , Pqcrypt needs structural changes and currently I am planning to use cloned liboqs folder to derive unique version of pqcrypt for issue #11

2023-10-07 11:23 UTC, Anish-M-code commented
I feel it would be better if we could combine run.sh as well in a similar way making pqcrypt easy to use.

2023-10-07 11:50 UTC, ATamblingPoder commented
> I feel it would be better if we could combine run.sh as well in a similar way making pqcrypt easy to use.

Yeah I think that'll much better! Meanwhile I've removed the rm line and I'll start work on this soon

2023-10-12 16:59 UTC, merged

2023-10-12 16:59 UTC, Anish-M-code commented
@ATamblingPoder Thanks for contributing !